development:
  adapter: postgresql
  encoding: unicode
  database: sample_to_heroku_development
  pool: 5
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: sample_to_heroku_test
  pool: 5
  username: postgres
  password: postgres